[colors]
[colors.primary]
background = "#241b2f"
foreground = "#ffffff"

[colors.normal]
black   = "#241b2f"
red     = "#fe4450"
green   = "#72f1b8"
yellow  = "#fede5d"
blue    = "#03edf9"
magenta = "#ff7edb"
cyan    = "#36f9f6"
white   = "#f7f7f7"

[colors.bright]
black   = "#495495"
red     = "#fe4450"
green   = "#72f1b8"
yellow  = "#fede5d"
blue    = "#03edf9"
magenta = "#ff7edb"
cyan    = "#36f9f6"
white   = "#ffffff"

[colors.cursor]
text   = "#241b2f"
cursor = "#ffffff"
